spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/fee_local # 개발
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always # 개발
    data: classpath*:data_real.sql # 파일명 변경 후 사용
  jpa:
    hibernate:
      ddl-auto: create # 개발
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
  # 메시지 파일 등록
  messages:
    basename: messages,errors

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
