spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fee?useSSL=false&allowPublicKeyRetrieval=true
    username: yaddoong
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    data: classpath*:data_real.sql # 파일명 변경 후 사용
  jpa:
    hibernate:
      ddl-auto: update # 변경분만 반영
      # ddl-auto: create 테이블이 있으면 drop 하고 새로 만든다.
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        use_sql_comments: true
  # 메시지 파일 등록
  messages:
    basename: messages,errors

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace